spring:
  application:
    name: movie
  data:
    redis:
      #host: localhost
      host: toughbox.iptime.org
      password:
      database: 0
      port: 6379

server:
  port: 8083
  #port: 8080

base-url:
  auth: http://localhost:8081/api/v1

jwt:
  signing-key: YWJjZGVmZw==
