FROM openjdk:21-jre-slim
LABEL authors="tough"

COPY build/libs/*.jar bucket.jar

RUN addgroup --system builder && adduser --system builder --ingroup builder
USER builder:builder

EXPOSE 8082
ENTRYPOINT ["java", "-jar", "/bucket.jar"]