FROM amazoncorretto:21
LABEL authors="tough"

COPY build/libs/*.jar bucket.jar

RUN groupadd -r builder && useradd -r -g builder builder

RUN addgroup --system builder && adduser --system builder --ingroup builder
USER builder:builder

EXPOSE 8082
ENTRYPOINT ["java", "-jar", "/bucket.jar"]