version: '3'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: 'auth'
      MYSQL_USER: 'tough'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql

  minio:
    image: minio/minio
    container_name: minio-container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: tough
      MINIO_ROOT_PASSWORD: 12345678 #기본 8자리 지정하지 않으면 실행 안됨
    volumes:
      - /home/tough/project/minio:/data
    command: server /data --console-address ":9001"