spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth
              uri: http://localhost:8081
              order: 1
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /api/v1/$\{segment}
            - id: bucket
              uri: http://localhost:8082
              order: 1
              predicates:
                - Path=/bucket/**
              filters:
                - RewritePath=/bucket/(?<segment>.*), /api/v1/$\{segment}
          globals:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:8090"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600

jwt:
  secret: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e