spring:
  application:
    name: auth
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://toughbox.iptime.org:3306/auth
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: tough
      password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    database: mysql
    show-sql: true
  #sql:
  #  init:
  #    mode: always
  #    schema-locations: classpath:sql/schema.sql

server:
  port: 8081
  address: 0.0.0.0

jwt:
  secret: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.server.adapter: DEBUG

management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted