FROM openjdk:21-jre-slim
LABEL authors="tough"

COPY build/libs/*.jar movie.jar

RUN addgroup --system builder && adduser --system builder --ingroup builder
USER builder:builder

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/movie.jar"]