FROM amazoncorretto:21
LABEL authors="tough"

COPY build/libs/*.jar movie.jar

# adduser, addgroup 설치
RUN apt-get update && apt-get install -y --no-install-recommends adduser \
    && rm -rf /var/lib/apt/lists/*

RUN addgroup --system builder && adduser --system builder --ingroup builder
USER builder:builder

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/movie.jar"]