FROM amazoncorretto:21
LABEL authors="tough"

COPY build/libs/*.jar movie.jar

# groupadd, useradd 설치
RUN yum install -y shadow-utils && yum clean all

RUN groupadd -r builder && useradd -r -g builder builder

RUN addgroup --system builder && adduser --system builder --ingroup builder
USER builder:builder

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/movie.jar"]